const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states=['جديدة','قيد التنفيذ','بانتظار إفادة','للمراجعة','مكتملة'];
const mime={xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',xls:'application/vnd.ms-excel',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',doc:'application/msword',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation',ppt:'application/vnd.ms-powerpoint',pdf:'application/pdf',csv:'text/csv',txt:'text/plain',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',zip:'application/zip'};
let db,me,profiles=[],tasks=[],events=[],view='tasks',query='',filter='',timer,refreshing=false,recovering=location.hash.includes('type=recovery');
const manager=()=>me?.role==='manager';
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Riyadh'});
const overdue=t=>t.status!==4&&t.due_date<today();
const name=id=>profiles.find(p=>p.id===id)?.display_name||'عضو الفريق';
const badge=t=>`<span class="badge s${t.status}">${states[t.status]}</span>`;
function notice(message){$('#message').textContent=message;$('#message').classList.toggle('hidden',!message)}
function authMessage(message,error=false){$('#auth-message').textContent=message;$('#auth-message').classList.toggle('error',error)}
function errorText(e){let msg=e?.message||'';if(msg.includes('REPLY_REQUIRED'))return 'اكتبي الرد أو إفادة المعالجة قبل الحفظ.';if(msg.includes('CONFLICT'))return 'تم تحديث البيانات من مستخدم آخر. أغلقي النافذة وحدّثي الصفحة ثم حاولي مجددًا.';if(msg.includes('FORBIDDEN'))return 'ليس لديك صلاحية لهذا الإجراء.';if(msg.includes('USER_NOT_VERIFIED'))return 'على الموظف إنشاء حساب وتأكيد بريده أولًا.';if(msg.includes('MANAGER_APPROVAL_REQUIRED'))return 'اعتماد الإغلاق أو إعادة الفتح من صلاحية المدير المرسل فقط.';if(msg.includes('Invalid login'))return 'البريد أو كلمة المرور غير صحيحين.';if(msg.includes('Email not confirmed'))return 'يرجى تأكيد البريد الإلكتروني أولًا.';if(msg.includes('rate limit'))return 'وصلت الخدمة إلى حد المحاولات. انتظري قليلًا ثم أعيدي المحاولة.';return 'تعذر إكمال العملية. تحققي من الاتصال وإعدادات الخدمة والصلاحيات، ثم حاولي مجددًا.'}
function result(r){if(r.error)throw r.error;return r.data}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3000)}
async function busy(form,action,errorTarget){let buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await action()}catch(e){errorTarget(errorText(e))}finally{buttons.forEach(b=>b.disabled=false)}}
function modal(html){$('#modal').innerHTML=html;$('#modal').showModal();$('#modal').querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#modal').close())}
function modalError(s){let el=$('#modal-error');if(el)el.textContent=s;else toast(s)}
function signedOut(){clearInterval(timer);me=null;tickets=[];departments=[];view='tasks';profiles=[];tasks=[];events=[];$('#modal').close();$('#workspace').classList.add('hidden');$('#auth').classList.remove('hidden');$('#login').classList.remove('hidden')}
async function enter(){try{let session=result(await db.auth.getSession()).session;if(!session){signedOut();return}let own=result(await db.from('wf_profiles').select('*').eq('id',session.user.id).maybeSingle());if(!own||!own.active){signedOut();authMessage('تم تسجيل الدخول، لكن حسابك ينتظر تفعيل مدير المنصة.');return}me=own;$('#auth').classList.add('hidden');$('#workspace').classList.remove('hidden');$('#identity').textContent=me.display_name+' · '+(manager()?'مدير المنصة':me.role==='department_manager'?'مدير إدارة':'موظف');await refresh();clearInterval(timer);timer=setInterval(()=>{if(!document.hidden)refresh(false)},30000)}catch(e){authMessage(errorText(e),true)}}
async function refresh(show=true){if(refreshing||!me)return;refreshing=true;try{const data=await Promise.all([db.from('wf_profiles').select('*'),db.from('wf_tasks').select('*').order('created_at',{ascending:false}),db.from('wf_events').select('*').order('created_at',{ascending:false}).limit(500)]);const next=data.map(result);const current=next[0].find(p=>p.id===me.id);if(!current?.active){signedOut();authMessage('الحساب غير مفعّل.');return}profiles=next[0];tasks=next[1];events=next[2];me=current;await fetchTickets();notice('');if(show||!$('#modal').open)render()}catch(e){notice(errorText(e))}finally{refreshing=false}}
function render(){ ticketNavigation(); if(view==='tickets'){renderTickets();return;} $('#stats').innerHTML=[['إجمالي المهام',tasks.length],['متأخرة',tasks.filter(overdue).length],['بانتظار المراجعة',tasks.filter(t=>t.status===3).length],['مكتملة',tasks.filter(t=>t.status===4).length]].map(([label,n])=>`<div class="stat"><span class="muted">${label}</span><b>${n}</b></div>`).join('');$('#heading').textContent=view==='team'?'الفريق والإنجاز':view==='activity'?'سجل النشاط':manager()?'مهام الفريق':'مهامي'; if(view==='tasks'){$('#content').innerHTML=`<div class="row"><h2>${manager()?'مهام الفريق':'المهام المسندة إليّ'}</h2>${manager()?'<button id="new">+ إسناد مهمة</button>':''}</div><div class="filters"><input type="search" id="search" aria-label="البحث في المهام" placeholder="ابحث عن مهمة…" value="${esc(query)}"><select id="filter" aria-label="تصفية الحالة"><option value="">كل الحالات</option>${states.map((s,i)=>`<option value="${i}" ${filter===String(i)?'selected':''}>${s}</option>`).join('')}</select></div><div id="rows" class="table"></div>`;rows();$('#search').oninput=e=>{query=e.target.value;rows()};$('#filter').onchange=e=>{filter=e.target.value;rows()};if($('#new'))$('#new').onclick=newTask;}else if(view==='team'){$('#content').innerHTML=`<div class="row"><h2>توزيع العمل</h2>${manager()?'<button id="add-member">تفعيل حساب موظف</button>':''}</div><div class="members">${profiles.filter(p=>p.active&&p.role!=='department_manager').map(p=>{let a=tasks.filter(t=>t.assignee===p.id),done=a.filter(t=>t.status===4).length,pct=a.length?Math.round(100*done/a.length):0;return `<article class="stat"><h2>${esc(p.display_name)}</h2><p>${a.length} مهام · ${done} مكتملة</p><div class="bar"><span style="width:${pct}%"></span></div><div class="muted">إكمال المهام ${pct}٪</div></article>`}).join('')}</div>`;if($('#add-member'))$('#add-member').onclick=addMember;}else{$('#content').innerHTML='<h2>آخر التحديثات</h2>'+ (events.map(e=>`<div class="log"><strong>${esc(tasks.find(t=>t.id===e.task_id)?.title||'مهمة')}</strong><br>${esc(e.body)}<br><span class="muted">${esc(e.actor_name)} · ${new Date(e.created_at).toLocaleString('ar-SA')}</span></div>`).join('')||'<p class="empty">لا توجد تحديثات بعد.</p>')}}
function rows(){let a=tasks.filter(t=>t.title.includes(query)&&(filter===''||String(t.status)===filter));$('#rows').innerHTML=a.length?`<table><thead><tr><th>المهمة</th><th>المسؤول</th><th>موعد التسليم</th><th>الأولوية</th><th>الحالة</th><th>التفاصيل</th></tr></thead><tbody>${a.map(t=>`<tr><td><strong>${esc(t.title)}</strong></td><td>${esc(name(t.assignee))}</td><td class="${overdue(t)?'late':''}">${esc(t.due_date)}</td><td>${esc(t.priority)}</td><td>${badge(t)}</td><td><button class="link" data-id="${t.id}">فتح</button></td></tr>`).join('')}</tbody></table>`:'<p class="empty">لا توجد مهام مطابقة.</p>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>detail(b.dataset.id))}
function newTask(){modal(`<h2>إسناد مهمة جديدة</h2><form id="taskform"><label for="title">عنوان المهمة</label><input id="title" maxlength="150" required><label for="owner">المسؤول</label><select id="owner" required>${profiles.filter(p=>p.active&&p.role!=='department_manager').map(p=>`<option value="${p.id}">${esc(p.display_name)}</option>`).join('')}</select><label for="due">موعد التسليم</label><input id="due" type="date" required value="${today()}"><label for="priority">الأولوية</label><select id="priority"><option>عادية</option><option>متوسطة</option><option>عالية</option></select><label for="desc">وصف المطلوب</label><textarea id="desc" rows="3" maxlength="3000"></textarea><p id="modal-error" class="error" role="alert"></p><div class="actions"><button type="button" class="secondary" data-close>إلغاء</button><button>إسناد المهمة</button></div></form>`);$('#taskform').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{if(!$('#title').value.trim())throw Error();result(await db.rpc('wf_create_task',{p_title:$('#title').value.trim(),p_description:$('#desc').value,p_assignee:$('#owner').value,p_due:$('#due').value,p_priority:$('#priority').value}));$('#modal').close();await refresh();toast('تم حفظ المهمة')},modalError)}}
async function detail(id){const t=tasks.find(t=>t.id===id);if(!t)return;const locked=!manager()&&t.status===4;modal(`<h2>${esc(t.title)}</h2><p>${esc(t.description)}</p><div class="row">${badge(t)}<span>${esc(name(t.assignee))} · ${esc(t.due_date)}</span></div><form id="update"><label for="status">حالة المهمة</label><select id="status" ${locked?'disabled':''}>${states.map((s,i)=>`<option value="${i}" ${t.status===i?'selected':''} ${!manager()&&i===4?'disabled':''}>${s}</option>`).join('')}</select><label for="comment">تحديث أو ملاحظة</label><textarea id="comment" maxlength="3000" rows="3" ${locked?'disabled':''}></textarea>${locked?'<p class="muted">اعتمد المدير اكتمال المهمة.</p>':''}<p id="modal-error" class="error" role="alert"></p><div class="actions"><button type="button" class="secondary" data-close>إغلاق</button>${locked?'':'<button>حفظ التحديث</button>'}</div></form><hr><h3>المرفقات</h3><form id="upload"><label for="file">إضافة ملف — حتى ٢٠ ميجابايت</label><input id="file" type="file" accept=".xlsx,.xls,.docx,.doc,.pptx,.ppt,.pdf,.csv,.txt,.png,.jpg,.jpeg,.zip" required><button>رفع المرفق</button><p id="file-error" class="error" role="alert"></p></form><div id="files" class="muted">جاري تحميل المرفقات…</div><h3>سجل المهمة</h3><div id="task-events">جاري التحميل…</div>`);$('#update').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{result(await db.rpc('wf_update_task',{p_task:id,p_version:t.version,p_status:Number($('#status').value),p_comment:$('#comment').value.trim()}));$('#modal').close();await refresh();toast('تم حفظ التحديث')},modalError)};$('#upload').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{let f=$('#file').files[0],ext=f?.name.split('.').pop().toLowerCase();if(!f||!mime[ext]){throw {message:'INVALID_FILE'}}if(f.size>20*1024*1024){$('#file-error').textContent='الملف أكبر من ٢٠ ميجابايت.';return}let clean=f.name.replace(/[^a-zA-Z0-9. _-]/g,'_').slice(-140),path=id+'/'+crypto.randomUUID()+'--'+clean;result(await db.storage.from('wf-attachments').upload(path,f,{contentType:mime[ext],upsert:false}));$('#upload').reset();await loadFiles(id);toast('تم رفع المرفق')},s=>$('#file-error').textContent=s)};loadFiles(id);try{let logs=result(await db.from('wf_events').select('*').eq('task_id',id).order('created_at',{ascending:false}).limit(200));if($('#task-events'))$('#task-events').innerHTML=logs.map(l=>`<div class="log">${esc(l.body)}<br><span class="muted">${esc(l.actor_name)} · ${new Date(l.created_at).toLocaleString('ar-SA')}</span></div>`).join('')||'لا توجد تحديثات.'}catch(e){modalError(errorText(e))}}
async function loadFiles(id){try{let all=[],offset=0;for(;;){let batch=result(await db.storage.from('wf-attachments').list(id,{limit:100,offset,sortBy:{column:'created_at',order:'desc'}}));all.push(...batch.filter(x=>x.id));if(batch.length<100)break;offset+=100}if(!$('#files'))return;$('#files').innerHTML=all.map((f,i)=>`<div class="fileline"><span>${esc(f.name.split('--').slice(1).join('--')||f.name)}</span><button class="link" data-download="${i}">تنزيل</button></div>`).join('')||'<p>لا توجد مرفقات بعد.</p>';document.querySelectorAll('[data-download]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{let f=all[Number(b.dataset.download)],blob=result(await db.storage.from('wf-attachments').download(id+'/'+f.name)),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=f.name.split('--').slice(1).join('--')||f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){modalError(errorText(e))}finally{b.disabled=false}})}catch(e){if($('#files'))$('#files').textContent=errorText(e)}}
function addMember(){modal('<h2>تفعيل حساب موظف</h2><p>ينشئ الموظف حسابه من صفحة الدخول ويؤكد بريده، ثم يفعّله المدير هنا.</p><form id="member-form"><label for="member-name">اسم الموظف</label><input id="member-name" maxlength="100" required><label for="member-email">البريد الإلكتروني</label><input id="member-email" type="email" required><p id="modal-error" class="error" role="alert"></p><div class="actions"><button type="button" class="secondary" data-close>إلغاء</button><button>تفعيل كموظف</button></div></form>');$('#member-form').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{result(await db.rpc('wf_add_employee',{p_email:$('#member-email').value,p_name:$('#member-name').value.trim()}));$('#modal').close();await refresh();toast('تم تفعيل حساب الموظف')},modalError)}}
async function boot(){const c=window.WF_CONFIG;if(!c?.url||!c?.publishableKey){authMessage('خدمة حسابات الفريق والمرفقات قيد الإعداد. لم يتم تفعيل الدخول أو رفع الملفات بعد. يمكنك تجربة واجهة المهام من الرابط أدناه.');return}try{const {createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.117.2/+esm');db=createClient(c.url,c.publishableKey);$('#login').classList.remove('hidden');authMessage('ادخلي بحسابك للوصول إلى مهامك.');db.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY'){recovering=true;$('#auth').classList.remove('hidden');$('#workspace').classList.add('hidden');$('#login').classList.add('hidden');$('#recovery').classList.remove('hidden');authMessage('اختاري كلمة مرور جديدة.')}else if(event==='SIGNED_OUT')signedOut()});$('#login').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{result(await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value}));$('#password').value='';await enter()},s=>authMessage(s,true))};$('#register').onclick=()=>{if(!$('#login').reportValidity())return;busy($('#login'),async()=>{result(await db.auth.signUp({email:$('#email').value,password:$('#password').value,options:{emailRedirectTo:location.origin+location.pathname}}));$('#password').value='';authMessage('إذا كان البريد صالحًا للتسجيل، ستصلك رسالة تأكيد. بعد التأكيد يفعّل المدير حسابك. حساب الموظف لا يمنح صلاحية مدير.')},s=>authMessage(s,true))};$('#reset').onclick=()=>{if(!$('#email').reportValidity())return;busy($('#login'),async()=>{result(await db.auth.resetPasswordForEmail($('#email').value,{redirectTo:location.origin+location.pathname}));authMessage('إذا كان الحساب موجودًا، ستصلك رسالة لاستعادة كلمة المرور.')},s=>authMessage(s,true))};$('#recovery').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{result(await db.auth.updateUser({password:$('#new-password').value}));$('#new-password').value='';recovering=false;$('#recovery').classList.add('hidden');history.replaceState(null,'',location.pathname);await enter()},s=>authMessage(s,true))};$('#logout').onclick=async()=>{try{result(await db.auth.signOut());signedOut();authMessage('تم تسجيل الخروج.')}catch(e){notice(errorText(e))}};$('#refresh').onclick=()=>refresh();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));render()});if(!recovering)await enter();}catch(e){authMessage('تعذر الاتصال بخدمة الدخول. حاولي إعادة تحميل الصفحة.',true)}}

// Private department tickets. Authorization is also enforced by database and Storage policies.
let tickets=[],departments=[],ticketQuery='',ticketFilter='';
const ticketStates=['جديدة','قيد المعالجة','بانتظار إفادة','تمت المعالجة - بانتظار الاعتماد','مغلقة'];
const ticketUser=()=>manager()||me?.role==='department_manager';
const deptName=id=>departments.find(d=>d.id===id)?.name||'الإدارة';
async function fetchTickets(){
 if(!ticketUser()){tickets=[];departments=[];return;}
 const [a,b]=await Promise.all([db.from('wf_tickets').select('*').order('created_at',{ascending:false}),db.from('wf_departments').select('*').order('name')]);
 tickets=result(a);departments=result(b);
}
function ticketNavigation(){
 let button=$('[data-view="tickets"]');
 if(!button){button=document.createElement('button');button.dataset.view='tickets';button.textContent='تذاكر الإدارات';$('nav').append(button);button.onclick=()=>{view='tickets';render()};}
 button.classList.toggle('hidden',!ticketUser());
 if(me?.role==='department_manager')view='tickets';
 if(!ticketUser()&&view==='tickets')view='tasks';
 document.querySelectorAll('[data-view]').forEach(b=>{if(b.dataset.view!=='tickets')b.classList.toggle('hidden',me?.role==='department_manager');b.classList.toggle('active',b.dataset.view===view)});
 $('nav').style.flexWrap='wrap';
}
function renderTickets(){
 $('#heading').textContent=manager()?'تذاكر الإدارات':'تذاكر إدارتي';
 $('#stats').innerHTML=[['إجمالي التذاكر',tickets.length],['متأخرة',tickets.filter(t=>t.status!==4&&t.due_date<today()).length],['بانتظار الاعتماد',tickets.filter(t=>t.status===3).length],['مغلقة',tickets.filter(t=>t.status===4).length]].map(([label,n])=>`<div class="stat"><span class="muted">${label}</span><b>${n}</b></div>`).join('');
 $('#content').innerHTML=`<div class="row"><h2>${manager()?'التذاكر التي أرسلتها':'التذاكر الواردة لإدارتي'}</h2>${manager()?'<button id="new-ticket">+ إرسال تذكرة</button>':''}</div><p class="muted">${manager()?'الردود والمرفقات متاحة لك ولإدارة التذكرة. اعتماد الإغلاق من صلاحيتك.':'يمكنك الرد وإرفاق المخرجات وطلب اعتماد المعالجة. يعتمد المرسل الإغلاق.'}</p><div class="filters"><input id="ticket-search" type="search" aria-label="البحث بالتذاكر" placeholder="رقم التذكرة أو الموضوع أو الإدارة" value="${esc(ticketQuery)}"><select id="ticket-filter" aria-label="حالة التذكرة"><option value="">كل الحالات</option>${ticketStates.map((s,i)=>`<option value="${i}" ${ticketFilter===String(i)?'selected':''}>${s}</option>`).join('')}</select></div><div class="table" id="ticket-rows"></div>`;
 $('#ticket-search').oninput=e=>{ticketQuery=e.target.value;ticketRows()};$('#ticket-filter').onchange=e=>{ticketFilter=e.target.value;ticketRows()};if($('#new-ticket'))$('#new-ticket').onclick=newTicket;ticketRows();
}
function ticketRows(){
 const rows=tickets.filter(t=>(t.title+' '+t.number+' '+deptName(t.department_id)).includes(ticketQuery)&&(ticketFilter===''||String(t.status)===ticketFilter));
 $('#ticket-rows').innerHTML=rows.length?`<table><thead><tr><th>التذكرة</th><th>الإدارة</th><th>الموعد المستهدف</th><th>الأولوية</th><th>الحالة</th><th></th></tr></thead><tbody>${rows.map(t=>`<tr><td><strong>#${t.number} · ${esc(t.title)}</strong></td><td>${esc(deptName(t.department_id))}</td><td class="${t.status!==4&&t.due_date<today()?'late':''}">${esc(t.due_date)}</td><td>${esc(t.priority)}</td><td><span class="badge s${t.status}">${ticketStates[t.status]}</span></td><td><button class="link" data-ticket="${t.id}">فتح</button></td></tr>`).join('')}</tbody></table>`:'<p class="empty">لا توجد تذاكر مطابقة.</p>';
 document.querySelectorAll('[data-ticket]').forEach(b=>b.onclick=()=>ticketDetail(b.dataset.ticket));
}
function newTicket(){
 if(!manager())return;
 modal(`<h2>إرسال تذكرة للإدارة</h2><form id="ticket-create"><label for="ticket-dept">الإدارة المستقبلة</label><select id="ticket-dept" required>${departments.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select><label for="ticket-title">الموضوع</label><input id="ticket-title" maxlength="150" required><label for="ticket-desc">تفاصيل الطلب</label><textarea id="ticket-desc" rows="4" maxlength="5000" required></textarea><label for="ticket-due">الموعد المستهدف</label><input id="ticket-due" type="date" value="${today()}" required><label for="ticket-priority">الأولوية</label><select id="ticket-priority"><option>عادية</option><option>متوسطة</option><option>عالية</option></select><p class="muted">تظهر التذكرة داخل حساب مدير الإدارة. يمكن إضافة المرفقات بعد الإرسال. لا تُرسل رسالة بريد تلقائية.</p><p id="modal-error" class="error" role="alert"></p><div class="actions"><button type="button" class="secondary" data-close>إلغاء</button><button>إرسال التذكرة</button></div></form>`);
 $('#ticket-create').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{const id=result(await db.rpc('wf_ticket_create',{p_title:$('#ticket-title').value.trim(),p_description:$('#ticket-desc').value.trim(),p_department:$('#ticket-dept').value,p_due:$('#ticket-due').value,p_priority:$('#ticket-priority').value}));$('#modal').close();await refresh();await ticketDetail(id);toast('تم إرسال التذكرة')},modalError)};
}
async function ticketDetail(id){
 const t=tickets.find(t=>t.id===id);if(!t)return;
 const owner=t.created_by===me.id,locked=t.status===4&&!owner;
 modal(`<h2>#${t.number} · ${esc(t.title)}</h2><p class="muted">${esc(deptName(t.department_id))} · ${esc(t.due_date)} · ${esc(t.priority)}</p><p style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(t.description)}</p><form id="ticket-update"><label for="ticket-status">الحالة</label><select id="ticket-status" ${locked?'disabled':''}>${ticketStates.map((s,i)=>`<option value="${i}" ${t.status===i?'selected':''} ${!owner&&i===4?'disabled':''}>${s}</option>`).join('')}</select><label for="ticket-reply">الرد أو إفادة المعالجة</label><textarea id="ticket-reply" rows="3" maxlength="5000" ${locked?'disabled':''}></textarea><p id="modal-error" role="alert" class="error"></p><div class="actions"><button type="button" data-close class="secondary">إغلاق النافذة</button>${locked?'':'<button>حفظ الرد والحالة</button>'}</div></form><h3>مرفقات التذكرة</h3>${t.status!==4?'<form id="ticket-upload"><label for="ticket-file">ملف حتى ٢٠ ميجابايت</label><input id="ticket-file" type="file" required accept=".xlsx,.xls,.docx,.doc,.pptx,.ppt,.pdf,.csv,.txt,.png,.jpg,.jpeg,.zip"><button>رفع المرفق</button><p id="ticket-file-error" class="error" role="alert"></p></form>':'<p class="muted">التذكرة مغلقة. أعيدي فتحها لإضافة مرفقات.</p>'}<div id="ticket-files">جاري تحميل المرفقات…</div><h3>الردود وسجل التذكرة</h3><div id="ticket-logs">جاري التحميل…</div>`);
 $('#modal').dataset.ticket=id;
 $('#ticket-update').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{result(await db.rpc('wf_ticket_update',{p_ticket:id,p_version:t.version,p_status:Number($('#ticket-status').value),p_reply:$('#ticket-reply').value.trim()}));$('#modal').close();await refresh();await ticketDetail(id);toast('تم حفظ التحديث')},modalError)};
 if($('#ticket-upload'))$('#ticket-upload').onsubmit=e=>{e.preventDefault();busy(e.target,async()=>{let f=$('#ticket-file').files[0],ext=f?.name.split('.').pop().toLowerCase();if(!f||!mime[ext]){$('#ticket-file-error').textContent='نوع الملف غير مدعوم.';return;}if(f.size>20*1024*1024){$('#ticket-file-error').textContent='الملف أكبر من ٢٠ ميجابايت.';return;}let clean=f.name.replace(/[^a-zA-Z0-9. _\u0600-\u06ff-]/g,'_').slice(-140);result(await db.storage.from('wf-ticket-files').upload(id+'/'+crypto.randomUUID()+'--'+clean,f,{contentType:mime[ext],upsert:false}));$('#ticket-upload').reset();await ticketFiles(id);toast('تم رفع المرفق')},s=>{$('#ticket-file-error').textContent=s})};
 await ticketFiles(id);
 try{const logs=result(await db.from('wf_ticket_events').select('*').eq('ticket_id',id).order('created_at',{ascending:false}));if($('#modal').dataset.ticket===id&&$('#ticket-logs'))$('#ticket-logs').innerHTML=logs.map(l=>`<div class="log"><div style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(l.body)}</div><span class="muted">${esc(l.actor_name)} · ${new Date(l.created_at).toLocaleString('ar-SA')}</span></div>`).join('');}catch(e){modalError(errorText(e))}
}
async function ticketFiles(id){
 try{let files=[],offset=0;for(;;){const batch=result(await db.storage.from('wf-ticket-files').list(id,{limit:100,offset}));files.push(...batch.filter(f=>f.id));if(batch.length<100)break;offset+=100;}
 if(!$('#ticket-files')||$('#modal').dataset.ticket!==id)return;
 $('#ticket-files').innerHTML=files.map((f,i)=>`<div class="fileline"><span>${esc(f.name.split('--').slice(1).join('--'))}</span><button class="link" data-ticket-file="${i}">تنزيل</button></div>`).join('')||'<p class="muted">لا توجد مرفقات.</p>';
 document.querySelectorAll('[data-ticket-file]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{let f=files[Number(b.dataset.ticketFile)],blob=result(await db.storage.from('wf-ticket-files').download(id+'/'+f.name)),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=f.name.split('--').slice(1).join('--');a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){modalError(errorText(e))}finally{b.disabled=false}});
 }catch(e){if($('#ticket-files'))$('#ticket-files').textContent=errorText(e)}
}
$('#register').textContent='إنشاء حساب';
boot();
